framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true


    cache:
    # Unique name of your app: used to compute stable namespaces for cache keys.
    #prefix_seed: your_vendor_name/app_name

    # The "app" cache stores to the filesystem by default.
    # The data in this cache should persist between deploys.
    # Other options include:

    # Redis
    #app: cache.adapter.redis
    #default_redis_provider: redis://localhost

    # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        app: cache.adapter.apcu

    # Namespaced pools use the above "app" backend by default
    #pools:
    #my.dedicated.cache: null