twig:
    default_path: '%kernel.project_dir%/templates'
    
        # On déclare ci-dessous le nom de la variable globale
    globals:
        locales: '%app.locales%'

    paths:
        # '%kernel.project_dir%/templates/post': post
        'public/css': styles
